import type { CallRecord } from "../screens/App/Calls/data/callRecords";

export const EXTRA_CALL_RECORDS: CallRecord[] = [
  {
    id: "extra-1",
    conversationId: "6",
    contactName: "Linda Okafor",
    contactRole: "Patient",
    phone: "(713) 555-0189",
    direction: "inbound",
    callType: "Direct",
    timestamp: "Today, 8:12 AM",
    sortKey: 130,
    durationSeconds: 0,
    isMissed: true,
    isConference: false,
    isVoicemail: false,
    isVoicemailListened: false,
    hasRecording: false,
  },
  {
    id: "extra-2",
    conversationId: "17",
    contactName: "Dr. David Nguyen",
    contactRole: "Endocrinologist",
    phone: "(480) 555-0177",
    direction: "outbound",
    callType: "Conference",
    timestamp: "Yesterday, 4:45 PM",
    sortKey: 129,
    durationSeconds: 1560,
    isMissed: false,
    isConference: true,
    isVoicemail: false,
    isVoicemailListened: false,
    hasRecording: true,
    recordingId: "REC-extra-2",
  },
  {
    id: "extra-3",
    conversationId: "3",
    contactName: "Riverside Clinic",
    contactRole: "Clinic",
    phone: "(818) 555-0076",
    direction: "inbound",
    callType: "Transfer",
    timestamp: "Yesterday, 11:20 AM",
    sortKey: 128,
    durationSeconds: 245,
    isMissed: false,
    isConference: false,
    isVoicemail: false,
    isVoicemailListened: false,
    hasRecording: true,
    recordingId: "REC-extra-3",
  },
  {
    id: "extra-4",
    conversationId: "27",
    contactName: "William Hayes",
    contactRole: "Patient",
    phone: "(617) 555-0266",
    direction: "inbound",
    callType: "Direct",
    timestamp: "Mon, 6:30 PM",
    sortKey: 127,
    durationSeconds: 0,
    isMissed: true,
    isConference: false,
    isVoicemail: false,
    isVoicemailListened: false,
    hasRecording: false,
  },
  {
    id: "extra-5",
    conversationId: "10",
    contactName: "Southside Pharmacy",
    contactRole: "Pharmacy",
    phone: "(770) 555-0099",
    direction: "outbound",
    callType: "Direct",
    timestamp: "Sat, 2:15 PM",
    sortKey: 126,
    durationSeconds: 198,
    isMissed: false,
    isConference: false,
    isVoicemail: false,
    isVoicemailListened: false,
    hasRecording: true,
    recordingId: "REC-extra-5",
  },
  {
    id: "extra-vm-1",
    conversationId: "6",
    contactName: "Linda Okafor",
    contactRole: "Patient",
    phone: "(713) 555-0189",
    direction: "inbound",
    callType: "Direct",
    timestamp: "Today, 10:45 AM",
    sortKey: 133,
    durationSeconds: 43,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: false,
    hasRecording: false,
  },
  {
    id: "extra-vm-2",
    conversationId: "9",
    contactName: "Dr. Amara Nwosu",
    contactRole: "Neurologist",
    phone: "(646) 555-0023",
    direction: "inbound",
    callType: "Direct",
    timestamp: "Today, 9:12 AM",
    sortKey: 131,
    durationSeconds: 31,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: true,
    hasRecording: false,
  },
  {
    id: "extra-vm-3",
    conversationId: "5",
    contactName: "Dr. Sarah Chen",
    contactRole: "Oncologist",
    phone: "(617) 555-0211",
    direction: "outbound",
    callType: "Direct",
    timestamp: "Today, 11:30 AM",
    sortKey: 130,
    durationSeconds: 52,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: true,
    hasRecording: false,
  },
  {
    id: "extra-vm-4",
    conversationId: "17",
    contactName: "Dr. David Nguyen",
    contactRole: "Endocrinologist",
    phone: "(480) 555-0177",
    direction: "inbound",
    callType: "Direct",
    timestamp: "Yesterday, 3:15 PM",
    sortKey: 128,
    durationSeconds: 72,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: false,
    hasRecording: false,
  },
  {
    id: "extra-vm-5",
    conversationId: "3",
    contactName: "Riverside Clinic",
    contactRole: "Clinic",
    phone: "(818) 555-0076",
    direction: "inbound",
    callType: "Direct",
    timestamp: "Yesterday, 11:08 AM",
    sortKey: 127,
    durationSeconds: 58,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: true,
    hasRecording: false,
  },
  {
    id: "extra-vm-sent-1",
    conversationId: "2",
    contactName: "Dr. Raj Patel",
    contactRole: "Cardiologist",
    phone: "(212) 555-0198",
    direction: "outbound",
    callType: "Direct",
    timestamp: "Yesterday, 2:30 PM",
    sortKey: 126,
    durationSeconds: 28,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: true,
    hasRecording: false,
  },
  {
    id: "extra-vm-sent-2",
    conversationId: "10",
    contactName: "Southside Pharmacy",
    contactRole: "Pharmacy",
    phone: "(770) 555-0099",
    direction: "outbound",
    callType: "Direct",
    timestamp: "Yesterday, 5:40 PM",
    sortKey: 125,
    durationSeconds: 19,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: true,
    hasRecording: false,
  },
  {
    id: "extra-vm-6",
    conversationId: "21",
    contactName: "Metro Imaging Center",
    contactRole: "Imaging",
    phone: "(312) 555-0144",
    direction: "inbound",
    callType: "Direct",
    timestamp: "June 11, 2026, 2:20 PM",
    sortKey: 123,
    durationSeconds: 65,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: true,
    hasRecording: false,
  },
  {
    id: "extra-vm-7",
    conversationId: "15",
    contactName: "Dr. Elena Torres",
    contactRole: "Primary Care",
    phone: "(415) 555-0133",
    direction: "outbound",
    callType: "Direct",
    timestamp: "June 11, 2026, 9:05 AM",
    sortKey: 122,
    durationSeconds: 41,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: true,
    hasRecording: false,
  },
  {
    id: "extra-vm-8",
    conversationId: "9",
    contactName: "Dr. Amara Nwosu",
    contactRole: "Neurologist",
    phone: "(646) 555-0023",
    direction: "inbound",
    callType: "Direct",
    timestamp: "June 11, 2026, 4:50 PM",
    sortKey: 121,
    durationSeconds: 94,
    isMissed: false,
    isConference: false,
    isVoicemail: true,
    isVoicemailListened: true,
    hasRecording: false,
  },
];
