import type { FaxRecord } from "../screens/App/Messages/data/faxRecords";

export const MOCK_FAX_RECORDS: FaxRecord[] = [
  {
    id: "fax-1",
    conversationId: "2",
    contactName: "Dr. Raj Patel",
    contactRole: "Cardiologist",
    faxNumber: "(212) 555-0198",
    direction: "received",
    status: "delivered",
    documentName: "EKG_Results_Patient4821.pdf",
    pageCount: 3,
    fileSizeBytes: 202_752,
    timestamp: "Today, 10:45 AM",
    sortKey: 1000,
  },
  {
    id: "fax-2",
    conversationId: "5",
    contactName: "Dr. Sarah Chen",
    contactRole: "Oncologist",
    faxNumber: "(617) 555-0211",
    direction: "received",
    status: "delivered",
    documentName: "Pathology_Report_Martinez.pdf",
    pageCount: 8,
    fileSizeBytes: 1_245_600,
    coverNote: "Please review for shared patient consult.",
    timestamp: "Yesterday, 3:40 PM",
    sortKey: 900,
  },
  {
    id: "fax-3",
    conversationId: "7",
    contactName: "Quest Diagnostics",
    contactRole: "Laboratory",
    faxNumber: "(800) 555-0142",
    direction: "received",
    status: "delivered",
    documentName: "Lab_Panel_RKim_Complete.pdf",
    pageCount: 4,
    fileSizeBytes: 624_000,
    timestamp: "Yesterday, 6:00 AM",
    sortKey: 850,
  },
  {
    id: "fax-4",
    conversationId: "2",
    contactName: "Dr. Raj Patel",
    contactRole: "Cardiologist",
    faxNumber: "(212) 555-0198",
    direction: "sent",
    status: "sent",
    documentName: "Authorization_Request_4821.pdf",
    pageCount: 2,
    fileSizeBytes: 198_400,
    coverNote: "Prior auth for cardiac MRI — patient #4821.",
    timestamp: "Mon, 11:00 AM",
    sortKey: 800,
  },
  {
    id: "fax-5",
    conversationId: "9",
    contactName: "CVS Pharmacy",
    contactRole: "Pharmacy",
    faxNumber: "(415) 555-0188",
    direction: "sent",
    status: "failed",
    documentName: "Prescription_Metformin_Torres.pdf",
    pageCount: 1,
    fileSizeBytes: 96_000,
    coverNote: "New prescription — please confirm receipt.",
    timestamp: "Sat, 10:30 AM",
    sortKey: 750,
  },
  {
    id: "fax-6",
    conversationId: "11",
    contactName: "Northside Imaging",
    contactRole: "Clinic",
    faxNumber: "(312) 555-0166",
    direction: "received",
    status: "delivered",
    documentName: "MRI_Report_FollowUp.pdf",
    pageCount: 6,
    fileSizeBytes: 892_160,
    timestamp: "June 11, 2026, 2:15 PM",
    sortKey: 700,
  },
  {
    id: "fax-7",
    conversationId: "3",
    contactName: "Robert Kim",
    contactRole: "Patient",
    faxNumber: "(646) 555-0133",
    direction: "sent",
    status: "pending",
    documentName: "Care_Plan_Update_Q2.pdf",
    pageCount: 5,
    fileSizeBytes: 756_800,
    coverNote: "Updated care plan for your review.",
    timestamp: "Thu, 1:20 PM",
    sortKey: 650,
  },
  {
    id: "fax-8",
    conversationId: "14",
    contactName: "LabCorp",
    contactRole: "Laboratory",
    faxNumber: "(888) 555-0177",
    direction: "received",
    status: "delivered",
    documentName: "STAT_Toxicology_Final.pdf",
    pageCount: 2,
    fileSizeBytes: 224_000,
    timestamp: "Mon, 6:45 AM",
    sortKey: 600,
  },
  {
    id: "fax-9",
    conversationId: "6",
    contactName: "Memorial Radiology",
    contactRole: "Imaging",
    faxNumber: "(718) 555-0124",
    direction: "received",
    status: "delivered",
    documentName: "Radiology_Order_Confirm.pdf",
    pageCount: 2,
    fileSizeBytes: 156_800,
    timestamp: "Today, 8:20 AM",
    sortKey: 980,
  },
  {
    id: "fax-10",
    conversationId: "4",
    contactName: "Dr. Emily Watson",
    contactRole: "Primary Care",
    faxNumber: "(503) 555-0174",
    direction: "sent",
    status: "sent",
    documentName: "Patient_Intake_Form_4821.pdf",
    pageCount: 4,
    fileSizeBytes: 312_000,
    coverNote: "Completed intake for new patient referral.",
    timestamp: "Today, 7:05 AM",
    sortKey: 970,
  },
  {
    id: "fax-11",
    conversationId: "8",
    contactName: "Peak Physical Therapy",
    contactRole: "Clinic",
    faxNumber: "(206) 555-0191",
    direction: "received",
    status: "delivered",
    documentName: "PT_Evaluation_Report.pdf",
    pageCount: 5,
    fileSizeBytes: 445_440,
    timestamp: "Yesterday, 4:55 PM",
    sortKey: 880,
  },
  {
    id: "fax-12",
    conversationId: "10",
    contactName: "Dr. Marcus Webb",
    contactRole: "Endocrinologist",
    faxNumber: "(404) 555-0162",
    direction: "sent",
    status: "sent",
    documentName: "Referral_Endocrinology.pdf",
    pageCount: 3,
    fileSizeBytes: 267_520,
    coverNote: "Referral for glucose management consult.",
    timestamp: "Yesterday, 11:30 AM",
    sortKey: 870,
  },
  {
    id: "fax-13",
    conversationId: "12",
    contactName: "BlueCross Claims",
    contactRole: "Insurance",
    faxNumber: "(877) 555-0109",
    direction: "received",
    status: "delivered",
    documentName: "Billing_Statement_May.pdf",
    pageCount: 2,
    fileSizeBytes: 184_320,
    timestamp: "June 11, 2026, 9:40 AM",
    sortKey: 710,
  },
  {
    id: "fax-14",
    conversationId: "13",
    contactName: "Sunrise Clinic",
    contactRole: "Clinic",
    faxNumber: "(305) 555-0147",
    direction: "sent",
    status: "failed",
    documentName: "Clinic_Policies_Update.pdf",
    pageCount: 7,
    fileSizeBytes: 1_024_000,
    coverNote: "Updated clinic policies for partner offices.",
    timestamp: "June 11, 2026, 8:10 AM",
    sortKey: 705,
  },
];
