import type { FaxHistorySeed } from "./types";

export const FAX_HISTORY_SEEDS: FaxHistorySeed[] = [
  // Dr. Raj Patel — screenshot-style demo thread
  {
    id: "fxh-2-1",
    conversationId: "2",
    direction: "received",
    status: "delivered",
    documentName: "EKG_Results_Patient4821.pdf",
    pageCount: 3,
    fileSizeBytes: 202_752,
    timestamp: "Today, 10:45 AM",
    sortKey: 511,
  },
  {
    id: "fxh-2-2",
    conversationId: "2",
    direction: "sent",
    status: "sent",
    documentName: "Authorization_Request_4821.pdf",
    pageCount: 3,
    fileSizeBytes: 250_880,
    timestamp: "Today, 9:20 AM",
    sortKey: 510,
    coverNote: "Prior auth for cardiac MRI — patient #4821.",
  },
  {
    id: "fxh-2-3",
    conversationId: "2",
    direction: "sent",
    status: "failed",
    documentName: "Lab_Panel_Complete.pdf",
    pageCount: 1,
    fileSizeBytes: 83_968,
    timestamp: "Today, 8:05 AM",
    sortKey: 509,
  },
  {
    id: "fxh-2-4",
    conversationId: "2",
    direction: "received",
    status: "delivered",
    documentName: "Pathology_Report_Martinez.pdf",
    pageCount: 8,
    fileSizeBytes: 2_201_600,
    timestamp: "Yesterday, 3:45 PM",
    sortKey: 508,
    coverNote: "Please review for shared patient consult.",
  },
  {
    id: "fxh-2-5",
    conversationId: "2",
    direction: "sent",
    status: "failed",
    documentName: "Prescription_Medication_Torres.pdf",
    pageCount: 1,
    fileSizeBytes: 327_680,
    timestamp: "Yesterday, 10:30 AM",
    sortKey: 507,
    coverNote: "New prescription — please confirm receipt.",
  },
  {
    id: "fxh-2-6",
    conversationId: "2",
    direction: "received",
    status: "delivered",
    documentName: "MRI_Report_FollowUp.pdf",
    pageCount: 6,
    fileSizeBytes: 2_516_992,
    timestamp: "June 11, 2026, 5:00 PM",
    sortKey: 506,
  },
  {
    id: "fxh-2-7",
    conversationId: "2",
    direction: "received",
    status: "delivered",
    documentName: "Cardiology_Consult_Notes.pdf",
    pageCount: 4,
    fileSizeBytes: 512_000,
    timestamp: "June 11, 2026, 11:20 AM",
    sortKey: 505,
  },
  {
    id: "fxh-2-8",
    conversationId: "2",
    direction: "sent",
    status: "sent",
    documentName: "Referral_Packet_Q2.pdf",
    pageCount: 5,
    fileSizeBytes: 645_120,
    timestamp: "June 11, 2026, 8:40 AM",
    sortKey: 504,
  },
  {
    id: "fxh-2-9",
    conversationId: "2",
    direction: "received",
    status: "delivered",
    documentName: "Holter_Monitor_Strip.png",
    pageCount: 1,
    fileSizeBytes: 892_928,
    timestamp: "Today, 7:50 AM",
    sortKey: 503,
  },
  {
    id: "fxh-2-10",
    conversationId: "2",
    direction: "sent",
    status: "sent",
    documentName: "Discharge_Summary_Template.docx",
    pageCount: 3,
    fileSizeBytes: 234_496,
    timestamp: "Yesterday, 8:15 AM",
    sortKey: 502,
  },
  // Maria Gonzalez
  {
    id: "fxh-1-1",
    conversationId: "1",
    direction: "received",
    status: "delivered",
    documentName: "Lab_Results_Comprehensive.pdf",
    pageCount: 2,
    fileSizeBytes: 184_320,
    timestamp: "Today, 11:10 AM",
    sortKey: 411,
  },
  {
    id: "fxh-1-2",
    conversationId: "1",
    direction: "sent",
    status: "sent",
    documentName: "Appointment_Reminder_Letter.pdf",
    pageCount: 1,
    fileSizeBytes: 96_000,
    timestamp: "Yesterday, 4:20 PM",
    sortKey: 410,
  },
  {
    id: "fxh-1-3",
    conversationId: "1",
    direction: "received",
    status: "delivered",
    documentName: "Insurance_Authorization.pdf",
    pageCount: 3,
    fileSizeBytes: 278_528,
    timestamp: "June 11, 2026, 2:05 PM",
    sortKey: 409,
  },
  {
    id: "fxh-1-4",
    conversationId: "1",
    direction: "received",
    status: "delivered",
    documentName: "Patient_Consent_Form.docx",
    pageCount: 2,
    fileSizeBytes: 142_336,
    timestamp: "Today, 8:30 AM",
    sortKey: 408,
  },
  {
    id: "fxh-1-5",
    conversationId: "1",
    direction: "sent",
    status: "sent",
    documentName: "Care_Plan_Summary_Q2.doc",
    pageCount: 4,
    fileSizeBytes: 198_656,
    timestamp: "Today, 7:15 AM",
    sortKey: 407,
  },
  {
    id: "fxh-1-6",
    conversationId: "1",
    direction: "received",
    status: "delivered",
    documentName: "Wound_Photo_FollowUp.jpg",
    pageCount: 1,
    fileSizeBytes: 524_288,
    timestamp: "Yesterday, 11:45 AM",
    sortKey: 406,
  },
  {
    id: "fxh-1-7",
    conversationId: "1",
    direction: "sent",
    status: "failed",
    documentName: "Referral_Letter_Patel.docx",
    pageCount: 1,
    fileSizeBytes: 89_088,
    timestamp: "Yesterday, 9:20 AM",
    sortKey: 405,
  },
  {
    id: "fxh-1-8",
    conversationId: "1",
    direction: "received",
    status: "delivered",
    documentName: "XRay_Chest_Anterior.png",
    pageCount: 1,
    fileSizeBytes: 1_048_576,
    timestamp: "June 11, 2026, 4:30 PM",
    sortKey: 404,
  },
  {
    id: "fxh-1-9",
    conversationId: "1",
    direction: "sent",
    status: "sent",
    documentName: "Medication_List_Update.pdf",
    pageCount: 2,
    fileSizeBytes: 167_936,
    timestamp: "June 11, 2026, 10:10 AM",
    sortKey: 403,
  },
  // Elena Torres
  {
    id: "fxh-11-1",
    conversationId: "11",
    direction: "received",
    status: "delivered",
    documentName: "Imaging_Order_Confirmation.pdf",
    pageCount: 2,
    fileSizeBytes: 156_800,
    timestamp: "Today, 9:05 AM",
    sortKey: 311,
  },
  {
    id: "fxh-11-2",
    conversationId: "11",
    direction: "sent",
    status: "failed",
    documentName: "Prior_Auth_Imaging.pdf",
    pageCount: 4,
    fileSizeBytes: 389_120,
    timestamp: "Yesterday, 1:15 PM",
    sortKey: 310,
  },
  {
    id: "fxh-11-3",
    conversationId: "11",
    direction: "received",
    status: "delivered",
    documentName: "CT_Scan_Summary.jpg",
    pageCount: 1,
    fileSizeBytes: 712_704,
    timestamp: "Today, 7:55 AM",
    sortKey: 309,
  },
  {
    id: "fxh-11-4",
    conversationId: "11",
    direction: "sent",
    status: "sent",
    documentName: "Radiology_Referral.docx",
    pageCount: 2,
    fileSizeBytes: 156_672,
    timestamp: "Yesterday, 4:40 PM",
    sortKey: 308,
  },
  {
    id: "fxh-11-5",
    conversationId: "11",
    direction: "received",
    status: "delivered",
    documentName: "MRI_Report_FollowUp.pdf",
    pageCount: 6,
    fileSizeBytes: 2_516_992,
    timestamp: "June 11, 2026, 5:00 PM",
    sortKey: 307,
  },
];
