import type { VoicemailHistorySeed } from "./types";

export const VOICEMAIL_HISTORY_SEEDS: VoicemailHistorySeed[] = [
  // Elena Torres — screenshot-style demo thread
  {
    id: "vmh-11-1",
    conversationId: "11",
    direction: "inbound",
    timestamp: "Today, 10:45 AM",
    sortKey: 311,
    durationSeconds: 43,
  },
  {
    id: "vmh-11-2",
    conversationId: "11",
    direction: "inbound",
    timestamp: "Today, 9:18 AM",
    sortKey: 310,
    durationSeconds: 31,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-3",
    conversationId: "11",
    direction: "inbound",
    timestamp: "Today, 8:05 AM",
    sortKey: 309,
    durationSeconds: 52,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-4",
    conversationId: "11",
    direction: "inbound",
    timestamp: "Yesterday, 4:12 PM",
    sortKey: 308,
    durationSeconds: 67,
  },
  {
    id: "vmh-11-5",
    conversationId: "11",
    direction: "inbound",
    timestamp: "Yesterday, 11:30 AM",
    sortKey: 307,
    durationSeconds: 28,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-6",
    conversationId: "11",
    direction: "inbound",
    timestamp: "Yesterday, 8:45 AM",
    sortKey: 306,
    durationSeconds: 39,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-7",
    conversationId: "11",
    direction: "inbound",
    timestamp: "June 11, 2026, 2:20 PM",
    sortKey: 305,
    durationSeconds: 43,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-8",
    conversationId: "11",
    direction: "inbound",
    timestamp: "June 11, 2026, 11:15 AM",
    sortKey: 304,
    durationSeconds: 35,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-9",
    conversationId: "11",
    direction: "inbound",
    timestamp: "June 11, 2026, 9:05 AM",
    sortKey: 303,
    durationSeconds: 58,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-10",
    conversationId: "11",
    direction: "outbound",
    timestamp: "Today, 7:40 AM",
    sortKey: 302,
    durationSeconds: 24,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-11",
    conversationId: "11",
    direction: "outbound",
    timestamp: "Yesterday, 1:55 PM",
    sortKey: 301,
    durationSeconds: 41,
    isVoicemailListened: true,
  },
  {
    id: "vmh-11-12",
    conversationId: "11",
    direction: "outbound",
    timestamp: "June 11, 2026, 6:30 PM",
    sortKey: 300,
    durationSeconds: 72,
    isVoicemailListened: true,
  },
  // Maria Gonzalez
  {
    id: "vmh-1-1",
    conversationId: "1",
    direction: "inbound",
    timestamp: "Today, 7:22 AM",
    sortKey: 211,
    durationSeconds: 36,
  },
  {
    id: "vmh-1-2",
    conversationId: "1",
    direction: "inbound",
    timestamp: "Today, 6:10 AM",
    sortKey: 210,
    durationSeconds: 48,
    isVoicemailListened: true,
  },
  {
    id: "vmh-1-3",
    conversationId: "1",
    direction: "outbound",
    timestamp: "Yesterday, 5:10 PM",
    sortKey: 209,
    durationSeconds: 24,
    isVoicemailListened: true,
  },
  {
    id: "vmh-1-4",
    conversationId: "1",
    direction: "inbound",
    timestamp: "Yesterday, 2:35 PM",
    sortKey: 208,
    durationSeconds: 55,
    isVoicemailListened: true,
  },
  {
    id: "vmh-1-5",
    conversationId: "1",
    direction: "inbound",
    timestamp: "Yesterday, 9:50 AM",
    sortKey: 207,
    durationSeconds: 32,
    isVoicemailListened: true,
  },
  {
    id: "vmh-1-6",
    conversationId: "1",
    direction: "inbound",
    timestamp: "June 11, 2026, 3:40 PM",
    sortKey: 206,
    durationSeconds: 61,
    isVoicemailListened: true,
  },
  {
    id: "vmh-1-7",
    conversationId: "1",
    direction: "outbound",
    timestamp: "June 11, 2026, 10:20 AM",
    sortKey: 205,
    durationSeconds: 27,
    isVoicemailListened: true,
  },
  // Dr. James Patel
  {
    id: "vmh-2-1",
    conversationId: "2",
    direction: "inbound",
    timestamp: "Today, 11:02 AM",
    sortKey: 221,
    durationSeconds: 48,
    isVoicemailListened: true,
  },
  {
    id: "vmh-2-2",
    conversationId: "2",
    direction: "outbound",
    timestamp: "Yesterday, 2:30 PM",
    sortKey: 220,
    durationSeconds: 28,
    isVoicemailListened: true,
  },
  {
    id: "vmh-2-3",
    conversationId: "2",
    direction: "inbound",
    timestamp: "June 11, 2026, 4:50 PM",
    sortKey: 219,
    durationSeconds: 94,
    isVoicemailListened: true,
  },
  // Tyler Whitfield
  {
    id: "vmh-4-1",
    conversationId: "4",
    direction: "inbound",
    timestamp: "Yesterday, 2:55 PM",
    sortKey: 141,
    durationSeconds: 72,
  },
  {
    id: "vmh-4-2",
    conversationId: "4",
    direction: "outbound",
    timestamp: "June 11, 2026, 10:15 AM",
    sortKey: 140,
    durationSeconds: 19,
    isVoicemailListened: true,
  },
  // Linda Okafor
  {
    id: "vmh-6-1",
    conversationId: "6",
    direction: "inbound",
    timestamp: "Today, 10:45 AM",
    sortKey: 161,
    durationSeconds: 43,
  },
  {
    id: "vmh-6-2",
    conversationId: "6",
    direction: "inbound",
    timestamp: "Yesterday, 3:15 PM",
    sortKey: 160,
    durationSeconds: 55,
    isVoicemailListened: true,
  },
  // Dr. Sarah Chen
  {
    id: "vmh-5-1",
    conversationId: "5",
    direction: "outbound",
    timestamp: "Today, 11:30 AM",
    sortKey: 151,
    durationSeconds: 52,
    isVoicemailListened: true,
  },
  {
    id: "vmh-5-2",
    conversationId: "5",
    direction: "inbound",
    timestamp: "June 11, 2026, 1:40 PM",
    sortKey: 150,
    durationSeconds: 41,
    isVoicemailListened: true,
  },
  // Riverside Clinic
  {
    id: "vmh-3-1",
    conversationId: "3",
    direction: "inbound",
    timestamp: "Yesterday, 11:08 AM",
    sortKey: 131,
    durationSeconds: 58,
    isVoicemailListened: true,
  },
  // James Morrison
  {
    id: "vmh-12-1",
    conversationId: "12",
    direction: "inbound",
    timestamp: "Fri, 9:10 AM",
    sortKey: 121,
    durationSeconds: 72,
    isVoicemailListened: true,
  },
  // Dr. Robert Brooks
  {
    id: "vmh-28-1",
    conversationId: "28",
    direction: "inbound",
    timestamp: "Sun, 5:40 PM",
    sortKey: 111,
    durationSeconds: 58,
  },
];
